# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "CLDL"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "cldl"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

behind_proxy: 1

session: "YAML"
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag:    '[%'
      end_tag:      '%]'
      CACHE_SIZE:   64
      PRE_CHOMP:    2
      POST_CHOMP:   2
      TRIM:         1
      EVAL_PERL:    0
      ANYCASE:      1
      ENCODING:     'utf8'
      VARIABLES:
        # jquery
        jq_url:                   '//ajax.googleapis.com/ajax/libs/jquery/1.11.2'
        # Bootstrap
        bs_url:                   '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6'
        # Bootstrap-Table
        bs_tbl_url:               '//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1'
        # Not implemented
        bs_xedt_url:              '//cdnjs.cloudflare.com/ajax/libs/x-editable/1.9.1/bootstrap3-editable'
        app_host:                 'http://cldl2.example.com'
        app_host_url:             'http://cldl2.example.com'
        app_host_lib:             'http://cldl2.example.com/libs'
        cldl_menu_orientation:    'horizontal'
        cldl_logo:                '/images/cldl_logo_wb.svg'
        cldl_logo_sm:             '/images/cldl_logo_wb.svg'
        cldl_success_save:        'Successfully Saved'
        cldl_failed_save:         'NOT Successfully Saved'

  session:
    YAML:
      cookie_domain: "cldl2.example.com"
      session_dir: "/home/cldl/apps/CLDL/sessions"
      cookie_duration: 84600    # Default cookie timeout in seconds

#  serializer: JSON


plugins:
    Database:
        driver:        'mysql'
        database:      'cldl'
        host:          'localhost'
        port:          3306
        username:      'cldl_user'
        password:      'cldl_pass'
        dbi_params:
            RaiseError:         1
            PrintError:         0
            PrintWarn:          0
            ShowErrorStatement: 1
            AutoCommit:         1
        log_queries:   1


cldl:
  owner:            'cldl'
  base_url:         '/'
  login_url:        'login'
  splash_url:       'splash'
  upload_dir:       '/home/cldl/apps/CLDL/upload'
  upload_file_base: '/home/cldl/apps/CLDL'
  failed_login_log: 1
  failed_log_path:  '/home/cldl/apps/CLDL/logs/'
  failed_log_file:  'FAILED_LOGIN.log'



