INSERT INTO cldl_dvf VALUES 
(NULL,1,1,1,'dv_id','dv_id','ID',0,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,'README',NULL),
(NULL,1,1,2,'company_id','company_id','Company ID',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,3,'active','active','Active',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,4,'dv_name','dv_name','Name',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,5,'dv_db_table','dv_db_table','Table',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,6,'dv_type','dv_type','Type',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,7,'dv_title','dv_title','Title',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,8,'dt_add','dt_add','Add Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,9,'dt_del','dt_del','Delete Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,10,'dt_edit','dt_edit','Click to Edit',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,17,'dv_template','dv_template','Template',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,18,'dv_js_functions','dv_js_functions','JS',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,19,'dv_data_attributes','dv_data_attributes','Data Attributes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,20,'dv_notes','dv_notes','Notes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `cldl_dvf` VALUES 
(NULL,2,1,1,'dv_id','dv_id','ID',0,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,'README',NULL),
(NULL,2,1,2,'company_id','company_id','Company ID',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,3,'active','active','Active',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,4,'dv_name','dv_name','Name',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,5,'dv_db_table','dv_db_table','Table',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,6,'dv_type','dv_type','Type',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,7,'dv_title','dv_title','Title',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,8,'dt_add','dt_add','Add Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,9,'dt_del','dt_del','Delete Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,10,'dt_edit','dt_edit','Click to Edit',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,17,'dv_template','dv_template','Template',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,18,'dv_js_functions','dv_js_functions','JS',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,19,'dv_data_attributes','dv_data_attributes','Data Attributes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,20,'dv_notes','dv_notes','Notes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `cldl_dvf` VALUES (101225,15,1,1,'dvf_id','dvf_id','dvf_id',0,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101226,15,1,2,'dv_id','dv_id','dv_id',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101227,15,1,3,'active','active','active',5,NULL,NULL,0,1,NULL,1,NULL,NULL,'{ 0 => Inactive, 1 => Active }','1',NULL,NULL,NULL),(101228,15,1,4,'ordr','ordr','ordr',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101229,15,1,5,'dvf_db_column','dvf_db_column','dvf_db_column',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101230,15,1,6,'dvf_name','dvf_name','dvf_name',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101231,15,1,7,'dvf_label','dvf_label','dvf_label',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101232,15,1,8,'dvf_type','dvf_type','dvf_type',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101233,15,1,9,'dvf_placeholder','dvf_placeholder','dvf_placeholder',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101234,15,1,10,'dvf_help','dvf_help','dvf_help',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101235,15,1,11,'dvf_key','dvf_key','dvf_key',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101236,15,1,12,'dvf_sortable','dvf_sortable','dvf_sortable',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101237,15,1,13,'dvf_sort_ordr','dvf_sort_ordr','dvf_sort_ordr',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101238,15,1,14,'dvf_sort_asc_desc','dvf_sort_asc_desc','dvf_sort_asc_desc',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101239,15,1,15,'dvf_before_display','dvf_before_display','dvf_before_display',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101240,15,1,16,'dvf_before_save','dvf_before_save','dvf_before_save',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101241,15,1,17,'dvf_values','dvf_values','dvf_values',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101242,15,1,18,'dvf_default_value','dvf_default_value','dvf_default_value',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101243,15,1,19,'dvf_js_functions','dvf_js_functions','dvf_js_functions',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101244,15,1,20,'dvf_data_attributes','dvf_data_attributes','dvf_data_attributes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(101245,15,1,21,'dvf_notes','dvf_notes','dvf_notes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
