INSERT INTO cldl_dvf VALUES 
(NULL,1,1,1,'dv_id','dv_id','ID',0,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,'README',NULL),
(NULL,1,1,2,'company_id','company_id','Company ID',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,3,'active','active','Active',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,4,'dv_name','dv_name','Name',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,5,'dv_db_table','dv_db_table','Table',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,6,'dv_type','dv_type','Type',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,7,'dv_title','dv_title','Title',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,8,'dt_add','dt_add','Add Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,9,'dt_del','dt_del','Delete Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,10,'dt_edit','dt_edit','Click to Edit',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,17,'dv_template','dv_template','Template',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,18,'dv_js_functions','dv_js_functions','JS',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,19,'dv_data_attributes','dv_data_attributes','Data Attributes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,1,1,20,'dv_notes','dv_notes','Notes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `cldl_dvf` VALUES 
(NULL,2,1,1,'dv_id','dv_id','ID',0,NULL,NULL,1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,'README',NULL),
(NULL,2,1,2,'company_id','company_id','Company ID',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,3,'active','active','Active',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,4,'dv_name','dv_name','Name',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,5,'dv_db_table','dv_db_table','Table',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,6,'dv_type','dv_type','Type',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,7,'dv_title','dv_title','Title',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,8,'dt_add','dt_add','Add Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,9,'dt_del','dt_del','Delete Button',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,10,'dt_edit','dt_edit','Click to Edit',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,17,'dv_template','dv_template','Template',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,18,'dv_js_functions','dv_js_functions','JS',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,19,'dv_data_attributes','dv_data_attributes','Data Attributes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(NULL,2,1,20,'dv_notes','dv_notes','Notes',0,NULL,NULL,0,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
